SELECT gv.HOTEN, COUNT(dt.MADT)  FROM dbo.THAMGIADT dt, dbo.GIAOVIEN gv
WHERE dt.MAGV = gv.MAGV
GROUP BY dt.MAGV, gv.HOTEN
HAVING COUNT(dt.MADT)>=2
GO
SELECT k.TENKHOA, bm.TENBM FROM dbo.KHOA k, dbo.GIAOVIEN gv, dbo.BOMON bm
WHERE bm.MABM=gv.MABM AND bm.MAKHOA=bm.MAKHOA
GROUP BY gv.MABM, bm.TENBM,k.TENKHOA
HAVING COUNT(gv.MABM)>=2

GO
DECLARE @luong float
SELECT @luong=luong FROM dbo.GIAOVIEN 
PRINT @luong