DROP DATABASE QLBD
GO

CREATE DATABASE QLBD
GO
USE QLBD
GO
CREATE TABLE CAUTHU
(
	MACT NUMERIC(18,0) IDENTITY(0,1),
	HOTEN NVARCHAR(50) NOT null ,
	VITRI NVARCHAR(50) NOT null,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(50) ,
	MACLB VARCHAR(5) NOT null,
	MAQG VARCHAR(5) NOT null,
	SO INT NOT null
	CONSTRAINT PK_CAUTHU PRIMARY KEY(MACT),
	
);

GO
CREATE TABLE QUOCGIA(
	MAQG VARCHAR(5) ,
	TENQG NVARCHAR(50)
	CONSTRAINT PK_QUOCGIA PRIMARY KEY (MAQG)
);

GO
CREATE TABLE CAULACBO(
	MACLB VARCHAR(5) ,
	TENCLB NVARCHAR(50),
	MASAN VARCHAR(5) NOT NULL,
	MATINH VARCHAR(5) NOT NULL,
	CONSTRAINT PK_CAULACBO PRIMARY KEY(MACLB)
)

GO
CREATE TABLE TINH(
	MATINH VARCHAR(5) ,
	TENTINH NVARCHAR(50)NOT NULL,
	
	CONSTRAINT TINH_PK PRIMARY KEY(MATINH)
)

GO
CREATE TABLE SANVD(
	MASAN VARCHAR(5) ,
	TENSAN NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50),

	CONSTRAINT SANVD_PK PRIMARY KEY(MASAN)
)

GO
CREATE TABLE HUANLUYENVIEN(
	MAHLV VARCHAR(5) ,
	TENHLV NVARCHAR(50) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(50),
	DIENTHOAI NVARCHAR(20),
	MAQG VARCHAR(5) NOT NULL,
	
	CONSTRAINT HLV_PK PRIMARY KEY(MAHLV)
)

GO
CREATE TABLE HLV_CLB(
	MAHLV VARCHAR(5) ,
	MACLB VARCHAR(5),
	VAITRO NVARCHAR(100),
	CONSTRAINT PK_HLV_CLB PRIMARY KEY(MAHLV,MACLB)
)
GO
CREATE TABLE TRANDAU(
	MATRAN NUMERIC IDENTITY(0,1),
	NAM INT NOT NULL,
	VONG INT NOT NULL,
	NGAYTD DATETIME NOT NULL,
	MACLB1 VARCHAR(5) NOT NULL,
	MACLB2 VARCHAR(5) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	KETQUA VARCHAR(5) NOT NULL,

	CONSTRAINT PK_TRANDAU PRIMARY KEY(MATRAN)
)
GO
CREATE TABLE BANGXH(
	MACLB VARCHAR(5) ,
	NAM INT  ,
	VONG INT ,
	SOTRAN INT NOT NULL ,
	THANG INT NOT NULL, 
	HOA INT NOT NULL,
	THUA INT NOT NULL,
	HIEUSO VARCHAR(5) NOT NULL,
	DIEM INT NOT NULL,
	HANG INT NOT NULL
	CONSTRAINT BANGXH_PK PRIMARY KEY(MACLB,NAM,VONG)
)

GO
CREATE TABLE THAMGIA(
	MATD NUMERIC ,
	MACT NUMERIC,
	SOTRAI INT ,

	CONSTRAINT THAMGIA_PK PRIMARY KEY(MATD,MACT)
)

GO
ALTER TABLE dbo.CAUTHU  ADD CONSTRAINT FK_CAUTHU_QUOCGIA FOREIGN KEY(MAQG) REFERENCES dbo.QUOCGIA(MAQG)
GO

ALTER TABLE dbo.CAUTHU ADD CONSTRAINT FK_CAUTHU_CAULACBO FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB)

GO
ALTER TABLE dbo.THAMGIA ADD CONSTRAINT FK_THAMGIA_CAUTHU FOREIGN KEY(MACT) REFERENCES dbo.CAUTHU(MACT),
CONSTRAINT FK_THAMGIA_TRANDAU FOREIGN KEY(MATD) REFERENCES dbo.TRANDAU(MATRAN)

GO
ALTER TABLE dbo.HLV_CLB ADD CONSTRAINT FK_HLV_CLB_HUANLUYENVIEN FOREIGN KEY(MAHLV) REFERENCES dbo.HUANLUYENVIEN(MAHLV),
CONSTRAINT FK_HLV_CLB_CAULACBO FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB)

GO
ALTER TABLE dbo.CAULACBO ADD CONSTRAINT FK_CAULACBO_TINH FOREIGN KEY(MATINH) REFERENCES dbo.TINH(MATINH),
CONSTRAINT FK_CAULACBO_SANVD FOREIGN KEY(MASAN) REFERENCES dbo.SANVD(MASAN) 

GO
ALTER TABLE dbo.BANGXH ADD CONSTRAINT FK_BANGXH_CAULACBO FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB)

GO
ALTER TABLE dbo.HLV_CLB ADD CONSTRAINT FK_HLV_CLB_HUANLUYENVIEN FOREIGN KEY(MAHLV) REFERENCES dbo.HUANLUYENVIEN(MAHLV)

GO
ALTER TABLE dbo.TRANDAU ADD CONSTRAINT FK_TRANDAU_SANVD FOREIGN KEY(MASAN) REFERENCES dbo.SANVD(MASAN),
CONSTRAINT FK_TRANDAU_CAULACBO1 FOREIGN KEY(MACLB1) REFERENCES dbo.CAULACBO(MACLB),
CONSTRAINT FK_TRANDAU_CAULACBO2 FOREIGN KEY(MACLB2) REFERENCES dbo.CAULACBO(MACLB)

GO
ALTER TABLE dbo.HUANLUYENVIEN ADD CONSTRAINT FK_HUANUYENVIEN_QUOCGIA FOREIGN KEY(MAQG) REFERENCES dbo.QUOCGIA(MAQG)

