GO
SELECT * FROM dbo.GIAOVIEN

--Tạo tran sử dụng rollback để trả về trạng thái ban đầu
BEGIN TRANSACTION Tran1
DELETE dbo.GIAOVIEN WHERE MAGV='013'
ROLLBACK TRANSACTION Tran1

--Tạo tran sử dụng COMMIT để cho phép thực thi 
BEGIN TRANSACTION Tran2
DELETE dbo.GIAOVIEN WHERE magv = '013'
COMMIT TRANSACTION Tran2

--Tạo nhiều tran với nhiều mốc thời gian khác nhau 
BEGIN TRANSACTION
SAVE TRANSACTION Tran3
DELETE dbo.GIAOVIEN WHERE MAGV='010'
COMMIT TRANSACTION Tran3
SAVE TRANSACTION Tran4
DELETE dbo.GIAOVIEN WHERE MAGV='009'
ROLLBACK TRANSACTION Tran3

GO
SELECT * FROM dbo.GIAOVIEN

