--Phần 1: Truy vấn cơ bản

--câu 1:
GO
	SELECT MACT, HOTEN,DIACHI,VITRI FROM dbo.CAUTHU WHERE MACLB='SDN'AND MAQG='BRA'
--câu 2:
GO
	SELECT a.HOTEN AS N'Tên cầu thủ' FROM dbo.CAUTHU a, dbo.THAMGIA b WHERE b.SOTRAI>=2 AND b.MACT=a.MACT
--câu 3:
--c1:
GO
	SELECT td.MATRAN,td.NGAYTD, s.TENSAN,c1.TENCLB,c2.TENCLB ,td.KETQUA FROM (SELECT * FROM dbo.TRANDAU WHERE VONG =3 AND nam=2009) td
																		JOIN dbo.CAULACBO c1 ON td.MACLB1 =c1.MACLB
																		JOIN dbo.CAULACBO c2 ON td.MACLB2 = c2.MACLB
																		JOIN dbo.SANVD s ON td.MASAN=s.MASAN
--c2:
GO
	SELECT td.MATRAN, td.NGAYTD, s.TENSAN,c1.TENCLB,c2.TENCLB, td.KETQUA FROM (SELECT * FROM dbo.TRANDAU WHERE vong =3 AND NAM=2009) td, dbo.CAULACBO c1, dbo.CAULACBO c2,  dbo.SANVD s

			WHERE td.MACLB1 = c1.MACLB AND td.MACLB2 = c2.MACLB AND td.MASAN=s.MASAN
--c3:
GO
	SELECT td.MATRAN,td.NGAYTD,s.TENSAN,c1.TENCLB,c2.TENCLB,td.KETQUA FROM dbo.TRANDAU td, dbo.CAULACBO c1, dbo.CAULACBO c2,dbo.SANVD s 
			WHERE td.VONG=3 AND td.nam=2009 AND td.MACLB1=c1.MACLB AND td.MACLB2=c2.MACLB AND td.MASAN=s.MASAN

--Câu 4: 
GO
	SELECT h.MAHLV, h.TENHLV, h.NGAYSINH,h.DIACHI, hc.VAITRO,c.TENCLB,q.TENQG  FROM dbo.HUANLUYENVIEN h, dbo.QUOCGIA q, dbo.HLV_CLB hc, dbo.CAULACBO c
													 WHERE h.MAQG=q.MAQG AND q.MAQG ='VN' AND h.MAHLV = hc.MAHLV AND c.MACLB = hc.MACLB

--Phần 2: Các phép toán trên nhóm

--câu 5:
GO
	SELECT c.MACLB, c.TENCLB,s.TENSAN,s.DIACHI,COUNT(ct.MACT) FROM dbo.CAULACBO c, dbo.SANVD s, dbo.CAUTHU ct
	WHERE c.MASAN=s.MASAN AND c.MACLB =ct.MACLB AND ct.MAQG!='VN'
	GROUP BY c.TENCLB,s.TENSAN,ct.MACLB,c.MACLB,s.DIACHI
	HAVING COUNT(ct.MACT) >=2
	
--câu 6:
GO
	SELECT t.TENTINH ,COUNT(c.MACT) FROM dbo.CAUTHU c, dbo.CAULACBO cl, dbo.TINH t
	WHERE c.MACLB = cl.MACLB AND cl.MATINH = t.MATINH AND c.VITRI=N'Tiền vệ'
	GROUP BY c.MACLB, t.TENTINH
--câu 7:
GO
	SELECT c.TENCLB , t.TENTINH, b.hang  FROM dbo.TINH t, dbo.CAULACBO c, dbo.BANGXH b
	WHERE b.MACLB = c.MACLB AND c.MATINH = t.MATINH AND b.VONG =3 AND b.NAM =2009 AND b.HANG= 1
	GROUP BY b.HANG, c.TENCLB , t.TENTINH

--Phần 3: Các toán tử nang cao 
--câu 8:
GO
	SELECT h.TENHLV FROM dbo.HUANLUYENVIEN h, dbo.HLV_CLB hc
	WHERE h.MAHLV = hc.MAHLV AND h.DIENTHOAI IS  NULL
--câu 9:
GO
	SELECT h.TENHLV FROM dbo.HUANLUYENVIEN h
	WHERE h.MAQG='VN' AND h.MAHLV NOT IN(SELECT MAHLV FROM dbo.HLV_CLB )
--câu 10:
GO
	SELECT c.HOTEN FROM dbo.BANGXH b, dbo.CAUTHU c
	WHERE b.VONG=3 AND b.NAM=2009 AND b.HANG >=3 AND b.HANG<=6 AND c.MACLB = b.MACLB
--câu 11:
GO 
	SELECT td.NGAYTD,s.TENSAN, c1.TENCLB, c2.TENCLB,td.KETQUA FROM (SELECT c.MACLB,b.NAM,b.VONG FROM dbo.BANGXH b, dbo.CAULACBO c WHERE b.NAM=2009 AND b.vong=3 AND b.MACLB =c.MACLB AND b.HANG=1 ) tb,dbo.TRANDAU td, dbo.CAULACBO c1, dbo.CAULACBO c2, dbo.SANVD s
	WHERE (td.MACLB1 = tb.MACLB OR td.MACLB2 = tb.MACLB) AND td.NAM =tb.NAM AND td.VONG=tb.VONG AND td.MACLB1=c1.MACLB AND td.MACLB2=c2.MACLB AND td.MASAN=s.MASAN
--c2:
	select DISTINCT NGAYTD,TENSAN,DOI1 ,DOI2,KETQUA
from (
	select DISTINCT NGAYTD,TENSAN,TENCLB AS DOI1 ,MACLB2,KETQUA
	from ( TRANDAU	JOIN CAULACBO  C ON TRANDAU.MACLB1=C.MACLB ) JOIN SANVD ON TRANDAU.MASAN=SANVD.MASAN
	WHERE VONG=3 AND NAM=2009 ) d1 JOIN
	(
	SELECT DISTINCT MACLB2, TENCLB AS DOI2
	FROM TRANDAU JOIN CAULACBO ON TRANDAU.MACLB2=CAULACBO.MACLB
	)d2 ON d1.MACLB2=d2.MACLB2
--Phần 4: Xử lý chuỗi ngày giờ :
--câu 12: 
GO
	--c1 :
	SELECT td.NGAYTD, c1.TENCLB, c2.TENCLB, td.KETQUA FROM dbo.TRANDAU td, dbo.CAULACBO c1,dbo.CAULACBO c2 
	WHERE td.MACLB1=c1.MACLB AND td.MACLB2=c2.MACLB AND MONTH(td.NGAYTD)=3 AND td.KETQUA LIKE '0%'
	--c2 :
	select DISTINCT  NGAYTD,DOI1 ,DOI2,KETQUA,MASAN,TENSAN FROM (select DISTINCT NGAYTD,TENCLB AS DOI1 ,MACLB2,KETQUA, TRANDAU.MASAN,TENSAN 
	FROM  TRANDAU	JOIN CAULACBO  C ON TRANDAU.MACLB1=C.MACLB JOIN SANVD ON TRANDAU.MASAN=SANVD.MASAN
	WHERE MONTH(NGAYTD)=3 AND KETQUA LIKE '0%') d1 JOIN(SELECT DISTINCT MACLB2, TENCLB AS DOI2
	FROM TRANDAU JOIN CAULACBO ON TRANDAU.MACLB2=CAULACBO.MACLB)d2 ON d1.MACLB2=d2.MACLB2
--câu 13 :
	SELECT * FROM dbo.CAUTHU c
	WHERE c.HOTEN LIKE N'% Công %'
--câu 14 :
	SELECT * FROM dbo.CAUTHU c WHERE c.HOTEN NOT LIKE N'Nguyễn%'
--câu 15 :
	SELECT * FROM dbo.HUANLUYENVIEN h WHERE YEAR(GETDATE())-YEAR(h.NGAYSINH)<=40 AND YEAR(GETDATE())-YEAR(h.NGAYSINH)>=35
--câu 16: 
	SELECT c.TENCLB , h.TENHLV, h.NGAYSINH FROM dbo.CAULACBO c, dbo.HUANLUYENVIEN h, dbo.HLV_CLB hc WHERE hc.MACLB=c.MACLB AND hc.MAHLV=h.MAHLV 
	AND DAY(h.NGAYSINH)=20 AND MONTH(h.NGAYSINH)=5 AND hc.VAITRO=N'HLV Chính' 
-- câu 17:
	SELECT TOP 1 c.TENCLB, t.TENTINH, SUM(CAST(SUBSTRING(b.HIEUSO,1,CHARINDEX('-',b.HIEUSO)-1)AS int)) AS N'Tổng bàn thắng' FROM dbo.BANGXH b, dbo.CAULACBO c, dbo.TINH t 
	WHERE b.MACLB = c.MACLB AND c.MATINH=t.MATINH
	GROUP BY b.MACLB, c.TENCLB, t.TENTINH
	ORDER BY SUM(CAST(LEFT(b.HIEUSO,1)AS int)) DESC
--Phần 5: Truy vấn con
--câu 18 :
GO
	SELECT clb.TENCLB, s.TENSAN, s.DIACHI,  COUNT(ct.HOTEN) N'Số lượng' FROM dbo.CAULACBO clb, dbo.CAUTHU ct, dbo.SANVD s
	WHERE clb.MACLB = ct.MACLB AND clb.MASAN=s.MASAN AND ct.MAQG !='VN'
	GROUP BY ct.MACLB ,clb.TENCLB,s.TENSAN,s.DIACHI
    HAVING COUNT(ct.HOTEN)>=2
--câu 19: 
GO
	 SELECT DISTINCT clb.TENCLB FROM dbo.CAULACBO clb, dbo.TINH t, dbo.BANGXH b,(SELECT TOP 1 clb1.MACLB, CAST(SUBSTRING(b1.HIEUSO,1,CHARINDEX('-',b1.HIEUSO)-1) AS int) - CAST(SUBSTRING(b1.HIEUSO,CHARINDEX('-',b1.HIEUSO)+1,LEN(b1.HIEUSO)-CHARINDEX('-',b1.HIEUSO))AS INT ) AS 'Max'  FROM dbo.BANGXH b1, dbo.CAULACBO clb1
	 WHERE clb1.MACLB = b1.MACLB
	 ORDER BY CAST(SUBSTRING(b1.HIEUSO,1,CHARINDEX('-',b1.HIEUSO)-1) AS int) - CAST(SUBSTRING(b1.HIEUSO,CHARINDEX('-',b1.HIEUSO)+1,LEN(b1.HIEUSO)-CHARINDEX('-',b1.HIEUSO))AS INT ) DESC) tb
	 WHERE b.MACLB = clb.MACLB AND clb.MATINH=t.MATINH AND tb.MACLB = clb.MACLB
--câu 20:
GO
	SELECT DISTINCT t.NGAYTD, s.TENSAN, c1.TENCLB,c2.TENCLB,t.KETQUA FROM dbo.CAULACBO c1, dbo.CAULACBO c2 , dbo.BANGXH b, dbo.SANVD s, dbo.TRANDAU t
	WHERE t.MACLB1 = c1.MACLB AND t.MACLB2= c2.MACLB AND t.MASAN=s.MASAN AND t.MACLB1 = b.MACLB AND b.HANG =(SELECT MAX(b1.HANG) FROM dbo.BANGXH b1) AND t.vong=3 AND t.nam=2009
--câu 21:
GO
	SELECT clb.TENCLB  FROM dbo.CAULACBO clb
	WHERE (SELECT COUNT(*) FROM dbo.TRANDAU t1 WHERE t1.MACLB1 = clb.MACLB OR  t1.MACLB2 = clb.MACLB) = (SELECT COUNT(*) FROM dbo.CAULACBO clb1 )-1
--câu 22:
GO
	SELECT clb.TENCLB FROM dbo.CAULACBO clb
	WHERE (SELECT COUNT(*) FROM dbo.TRANDAU t WHERE t.MACLB1 = clb.MACLB)=(SELECT COUNT(*) FROM dbo.CAULACBO c1)-1